import { Inter } from "next/font/google";
import Sidenav from "./components/sidenav";
import "../../(home)/globals.css";
import "react-toastify/dist/ReactToastify.css";
import { AuthProvider } from "../authcontext";
import ProtectedRoute from "../protectedroute";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Admin panel",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          <ProtectedRoute>
            <div className="bg-green-50 flex">
              <Sidenav />
              {children}
            </div>
          </ProtectedRoute>
        </AuthProvider>
      </body>
    </html>
  );
}
